### ISSUE TITLE
Usage of "fiber_storage" in the Win32 implementation

### ISSUE THREAD

**Issue by osor-io** [edubart/minicoro#13]
Hello! 😄 

I was trying to read up on good coroutine implementations to understand how they work. On the windows implementation I noticed that the `fiber_storage` member doesn't get initialized in `_mco_makectx`, so I believe it'll always be set to zero (cause of the `memset` in `_mco_create_context`).

https://github.com/edubart/minicoro/blob/4237c63c1b4acd04a00c6df454e02b034f6166f7/minicoro.h#L579

This gets set in the TIB when switching to the coroutine context. Is this on purpose? Do you know of anywhere I can read up on this?

Anecdotally, on my machine, on the main thread, that value seems to be set to 7680. Changing it to 0 doesn't seem to affect anything, possibly because that thread is not a fiber but I'm not sure.

Cheers!

Ruben.

**Comment by edubart** [comment]
> This gets set in the TIB when switching to the coroutine context. Is this on purpose?

This is on purpose, unfortunately there is little documentation about it. But basically Windows expects some values in TIB to change when switching context to perform run-time checks. That field is to store the "fiber data", as you can see in https://en.wikipedia.org/wiki/Win32_Thread_Information_Block or in https://github.com/wine-mirror/wine/blob/master/include/winnt.h#L2224 (the union, offset 0x20 of NT_TIB).

To make things happy on Windows we have to save/restore these 4 fields of TIB:
```
  void* fiber_storage;
  void* dealloc_stack;
  void* stack_limit;
  void* stack_base;
```

> Do you know of anywhere I can read up on this?

You can read a little about implementing coroutines on windows with assembly in https://graphitemaster.github.io/fibers/

Or looking Boost.Context in https://github.com/boostorg/context/blob/develop/src/asm/jump_x86_64_ms_pe_gas.asm

**Comment by osor-io** [comment]
Thanks so much for the info! I'll change my local implementation to account for the fiber storage. If I can I'll make sure to make it available here on GitHub as well 😊

The resources are great as well so closing the issue, thanks for taking the time.

Cheers!
