### ISSUE TITLE
Symmetric coroutines?

### ISSUE THREAD

**Issue by ib00** [edubart/minicoro#8]
Any plans to support symmetric coroutines?

**Comment by exebook** [comment]
Why? The two models actually have the same expressive power; i.e. asymmetric coroutines can be implemented using symmetric coroutines and vice versa. Providing both constructs only complicates the semantics of the coroutine mechanism, with no increase in its expressive power.

**Comment by edubart** [comment]
No plans, the library goal is to provide only Lua like coroutines, which are asymmetric. Also as mentioned, asymmetric coroutines are powerful enough to express symmetric coroutines.
